<?php

function views_field_defaults_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'views_ui_config_item_form'){

    $id = arg(5) . "-" . arg(6);

    $title = explode(':', $form['#title']);
    $title = str_replace(" ", "", strtolower($title[count($title)-1]));

    $defaults = array(
      'custom_label' => FALSE,
      'link_to_node' => FALSE,
      'element_type_enable' => TRUE,
      'element_label_type_enable' => TRUE,
      'element_wrapper_type_enable' => TRUE,
      'element_wrapper_class_enable' => TRUE,
      'element_default_classes' => FALSE,
      'element_type' => 0,
      'element_label_type' => 0,
      'element_wrapper_type' => 'div',
      'element_wrapper_class' => $title
    );

    foreach($defaults as $key => $default){
      if(!variable_get($id . '-' . $key)){
        $form['options'][$key]['#default_value'] = $default;
        variable_set($id . '-' . $key,TRUE);
      }
    }

  }
}
